config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/about'
  get 'comments/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :users,only:[:index,:show,:edit,:update]
  get 'unsubscribe' => 'users#unsubscribe'
  patch 'withdraw' => 'users#withdraw'
  resources :posts,only:[:index,:show,:new,:edit,:create,:update,:destroy]
  get 'confirm' => 'posts#confirm'
  post 'complete' => 'posts#complete'
  resources :likes,only:[:create,:destroy]
  resources :posts do  #postsコントローラへのルーティング
    resources :comments, only: [:index,:create]  #commentsコントローラへのルーティング
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments,dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :taggings, dependent: :destroy
  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  attachment :image
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
   before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

  def index
   @user = current_user
   @post_new = Post.new
   @users= User.all.where(is_deleted: false)
  end

  def show
    @user = User.find(params[:id])
    @post_new = Post.new
    @posts = Post.all.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user.id)
    end
  end


#   def create
    # @book = Book.new(book_params)
    # @book.user_id = current_user.id
#   if @book.save
#       flash[:notice]= 'You have created book successfully.'
#     redirect_to books_path(@book.id)
#   else
#     @book_each=Book.all
#     render action: :index
#   end
#   end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
       flash[:update]='You have updated user successfully.'
       redirect_to user_path(@user.id)
    else
       @user_each=post.all
       render action: :edit
    end
  end

def  withdraw
     current_user.update(is_deleted: true)
     reset_session
     redirect_to root_path
end

def usubscribe
end


  private

  def user_params
    params.require(:user).permit(:name, :image,:introduction,:is_deleted)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container  px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 col-mx-3">
<h1>User info</h1>
<%= form_with model:@user, local:true do |f| %>
<% if @user.errors.any? %>
  <div class="alert alert-warning">
  <h2><%= @user.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <p>Name</p>
  <%= f.text_field :name %>
  <p>Image</p>
   <%= f.attachment_field :image %>
  <p>Introduction</p>
  <%= f.text_area :introduction %>
<div class="visual">
<%= f.submit 'Update User',class:"btn btn-success"%>
</div>
<% end %>
<div class="button">
<%= link_to '退会する',  unsubscribe_path, class: 'btn btn-secondary' %>
</div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 col-mx-3">
<div class="color"><%= flash[:notice]%></div>
<div class="color"><%= flash[:update]%></div>

      <h1>User info</h1>
      <%= attachment_image_tag @user, :image, format: 'jpeg',  size: "100x100" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name </th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th> <%= @user.introduction %>  </th>
          </tr>
        </tbody>
      </table>
      <div class="userbtn">
        <p><%= link_to "", edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block fas fa-user-cog "  %></p>
      </div>

            <h3 class="mt-3">New post</h3>
      <%= form_with model:@post_new, local:true do |f| %>
      <% if @post_new.errors.any? %>
        <div class="alert alert-warning">
          <h2><%= @post_new.errors.count %> errors prohibited this image from being saved:</h2>
            <ul>
              <% @post_new.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
        </div>
            <% end %>

      <i class="fas fa-cat">Image</i>
      <%= f.attachment_field :image %>
      <i class="fas fa-flag">Title</i>
      <%= f.text_field :title, class: "form-control" %>
       <i class= "fas fa-user-edit">Introduction</i>
      <%= f.text_area :content, class: "form-control" %>
      <i class="fas fa-tag">tag</i>
       <%= f.text_field :tag_list, value: @post_new.tag_list.join(','), class: "form-control" %>
      <div class="btn">
        <%= f.submit 'Create Book',class:"btn btn-success" %>
            <% end %>
    </div>
  </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user_each| %>
            <tr>
              <td><%= attachment_image_tag user_each, :image, format: 'jpeg',  size: "40x40" %></td>
              <td><%= user_each.name %></td>
              <td><%= link_to "Show",user_path(user_each.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container  px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 col-mx-3">
<div class="color"><%= flash[:notice]%></div>
<div class="color"><%= flash[:update]%></div>

      <h1>User info</h1>
      <%= attachment_image_tag @user, :image, format: 'jpeg',  size: "100x100" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name </th>
            <th> <%= @user.name %></th>
          </tr>
          <tr>
            <th>Introduction </th>
            <th><%= @user.introduction %> </th>
          </tr>
        </tbody>
      </table>
      <div class="userbtan">
        <p><%= link_to "", edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block fas fa-user-cog "  %></p>
      </div>
        <h3 class="mt-3">New post</h3>
      <%= form_with model:@post_new, local:true do |f| %>
      <% if @post_new.errors.any? %>
        <div class="alert alert-warning">
          <h2><%= @post_new.errors.count %> errors prohibited this image from being saved:</h2>
            <ul>
              <% @post_new.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
        </div>
            <% end %>

      <i class="fas fa-cat">Image</i>
      <%= f.attachment_field :image %>
      <i class="fas fa-flag">Title</i>
      <%= f.text_field :title, class: "form-control" %>
       <i class= "fas fa-user-edit">Introduction</i>
      <%= f.text_area :content, class: "form-control" %>
      <i class="fas fa-tag">tag</i>
       <%= f.text_field :tag_list, value: @post_new.tag_list.join(','), class: "form-control" %>
      <div class="btn">
        <%= f.submit 'Create Book',class:"btn btn-success" %>
            <% end %>
      </div>
    </div>

   <div class="col-md-8 offset-md-1">
      <h2>matineko</h2>
      <table class="table">
         <thead>
          <tr>
            <th>Images</th>
            <th>Title</th>
            <th>Introduction</th>
            <th colspan="3"></th>
          </tr>
         </thead>
         <tbody>
          <% @posts.each do |post_each| %>
            <tr>
              <td><%= link_to post_path(post_each.id) do%>
                  <%= attachment_image_tag post_each, :image, format: 'jpeg',  size: "60x60" %>
                  <% end %></td>
              <td><%= link_to post_each.title, post_path(post_each.id) %></td>
              <td><%= post_each.content %></td>
              <td id="likes_buttons_<%= post_each.id %>">
              <%= post_each.likes.count %>
              <i class="fa fa-heart unlike-btn"></i>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto mt-5">

      <div class="text-center mt-5 mb-5">
        <h4><strong>本当に退会しますか？</strong></h4>
        <h6>
          退会すると、会員情報や<br>
          これまでの購入履歴が閲覧できなくなります。<br>
          退会する場合は「退会する」をクリックしてください。
        </h6>
      </div>

      <div class="row">
        <div class="col-md-7 mx-auto">

          <div class="row">
            <div class="col-md-6 text-center px-0 pb-5 pb-md-0">
              <%= link_to "退会しない", root_path, class:"btn btn-primary mt-3 px-4" %>
            </div>
            <div class="col-md-6 text-center p-0">
              <%= link_to "退会する", withdraw_path, method: :patch, data: {confirm: "退会しますか？"} ,class:"btn btn-danger mt-3 px-4" %>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>