config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/about'
  get 'comments/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :users,only:[:index,:show,:edit,:update]
  get 'unsubscribe' => 'users#unsubscribe'
  patch 'withdraw' => 'users#withdraw'
  resources :posts,only:[:index,:show,:new,:edit,:create,:update,:destroy]
  get 'confirm' => 'posts#confirm'
  post 'complete' => 'posts#complete'
  resources :likes,only:[:create,:destroy]
  resources :posts do  #postsコントローラへのルーティング
    resources :comments, only: [:index,:create]  #commentsコントローラへのルーティング
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/post.rb
class Post < ApplicationRecord
 has_many :likes, dependent: :destroy
 has_many :comments, dependent: :destroy
 has_many :taggings, dependent: :destroy
 belongs_to :user
  attachment :image # ここを追加（_idは含めません）
  acts_as_taggable #追加
  # acts_as_taggable_on :tags　と同じ意味のエイリアス
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

 def top
 end

 def index
   @post_new = Post.new
   @post = @search_post || Post.all.page(params[:page]).per(5)
   @user = current_user
   @tags = ActsAsTaggableOn::Tag.all
    # タグの一覧表示

   if params[:tag]
      @post = Post.tagged_with(params[:tag]).page(params[:page]).per(10)
      # タグ検索時にそのタグずけしているものを表示
   else
      @post = @search_post.page(params[:page]).per(5) || Post.all.page(params[:page]).per(5)
   end


 end


  def new
      @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @user = current_user
   if @post.save
    flash[:notice]= 'You have created book successfully.'
     redirect_to posts_path
   else
    render action: :show
   end
  end

  def update
    @post = Post.find(params[:id])
    @post.user_id = current_user.id
    @user = current_user
    if  @post.update(post_params)
       flash[:update]='You have updated book successfully.'
       redirect_to post_path(@post.id)
    else
       render action: :edit
    end
  end

  def show
   @user_id = current_user
   @post = Post.find(params[:id])
   @post_new = Post.new
   @user = @post.user
   @comments = @post.comments  #投稿詳細に関連付けてあるコメントを全取得
   @comment = current_user.comments.new  #投稿詳細画面でコメントの投稿を行うので、formのパラメータ用にCommentオブジェクトを取得
  end



  def edit
    @post=Post.find(params[:id])
    if @post.user != current_user
       redirect_to  post_path(@post.id)
    end
  end

  def destroy
   @post=Post.find(params[:id])
   @post.destroy
   redirect_to posts_path
  end



  private

  def post_params
    params.require(:post).permit(:title,:content,:image,:tag_list).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
 <% comments.each do |comment| %>
  <table>
   <tr>
     <td>
        <%= link_to user_path(comment.user.id) do%> <%= attachment_image_tag comment.user, :image, format: 'jpeg',  size: "20x20" , class:"mt-3 rounded-circle"; %><% end %>
       <i class="far fa-comment-dots"></i> <%= comment.comment %>
     </td>
   </tr>
 </table>
<% end %>

app/views/posts/_post.html.erb
<td>
  <%= link_to post_path(post.id) do%>
    <%=attachment_image_tag post, :image, format: 'jpeg',  size: "60x60"%>
  <%end%>
</td>

<td>
  <%= link_to post.title, post_path(post.id) %>
</td>

<td>
  <%= post.content %>
 </td>

<td id="likes_buttons_<%= post.id %>">
  <%= render "likes/like", post: post %>
</td>

<td class="label label-primary">
  <% post.tags.each do |tag|%>
     <%= link_to "#{tag.name}(#{tag.taggings_count})", posts_path(tag: tag.name), class: "label label-default" %>
  <%end%>
</td>
<td>
  <%= link_to 'Show', post %>
</td>

app/views/posts/_posts.html.erb
<% posts.each do |post_each| %>
<%= post_each.title %>
 <% end %>

app/views/posts/edit.html.erb
<div class="container  px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 col-mx-3">
<h1>投稿編集画面</h1>
<%= form_with model:@post, local:true do |f| %>
<% if @post.errors.any? %>
  <div class="alert alert-warning">
  <h2><%= @post.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

      <p>Image</p>
      <%= f.attachment_field :image %>
      <p>Title</p>
      <%= f.text_field :title, class: "form-control" %>
      <p>Introduction</p>
      <%= f.text_area :content, class: "form-control" %>
      <p>tag</p>
       <%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control" %>

 <div> <%= f.submit 'Update Post',class:"btn btn-success" %></div>
<% end %>
 <%= link_to "Show", post_path(@post.id) %>
 <%= link_to "Back",  posts_path %>
     </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container  px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 col-mx-3">
 <div class="color"><%= flash[:notice]%></div>
 <div class="color"><%= flash[:update]%></div>

            <h1>User info</h1>
            <%= attachment_image_tag @user, :image, format: 'jpeg',size: "100x100" %>
            <table class="table">
                <tbody>
                    <tr>
                       <th>name </th>
                       <th> <%= @user.name %></th>
                     </tr>
                     <tr>
                        <th>Introduction </th>
                        <th><%= @user.introduction %> </th>
                    </tr>
                </tbody>
            </table>
            <div class="userbtan">
                <p><%= link_to "", edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block fas fa-user-cog "  %></p>
            </div>

        <h3 class="mt-3">New post</h3>
      <%= form_with model:@post_new, local:true do |f| %>
      <% if @post_new.errors.any? %>
        <div class="alert alert-warning">
          <h2><%= @post_new.errors.count %> errors prohibited this image from being saved:</h2>
            <ul>
              <% @post_new.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
        </div>
            <% end %>

      <i class="fas fa-cat">Image</i>
      <%= f.attachment_field :image %>
      <i class="fas fa-flag">Title</i>
      <%= f.text_field :title, class: "form-control" %>
       <i class= "fas fa-user-edit">Introduction</i>
      <%= f.text_area :content, class: "form-control" %>
      <i class="fas fa-tag">tag</i>
       <%= f.text_field :tag_list, value: @post_new.tag_list.join(','), class: "form-control" %>
      <div class="btn">
        <%= f.submit 'Create Post',class:"btn btn-success" %>
            <% end %>
      </div>
    </div>
        <div class="col-md-8 offset-md-1">
            <h2>Matineko</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>Title</th>
                        <th>Introduction</th>
                        <th>like</th>
                        <th>tag</th>
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    <% @post.each do |post| %>
                        <tr>
                            <%= render 'post', post: post %>
                        </tr>
                     <% end %>
                </tbody>
            </table>
             <%#= render partial: 'posts/posts', locals: { posts: @search_post } %>
              <%= paginate @post %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div>
 <h1>新規投稿</h1>
</div>

<%= form_with model:@post, url: posts_path, method: :post,local:true do |f| %>
<!--<= form_for @item do |f| %>-->
     <div >
        <p >投稿画像</p>
        <%= f.attachment_field :image %>
     </div>

    <div >
      <p >タイトル</p>
      <%= f.text_field :name %>
    </div>

    <div >
      <p >イントロダクション</p>
      <%= f.text_area :introduction %>
    </div>

  <%= f.submit '新規登録', class: "btn btn-success" %>
 <% end %>

app/views/posts/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 col-mx-3">
      <div class="color"><%= flash[:notice]%></div>
      <div class="color"><%= flash[:update]%></div>

      <h1>User info</h1>
      <%= attachment_image_tag @user_id, :image, format: 'jpeg',  size: "100x100" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name </th>
            <th><%= @user_id.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th> <%= @user_id.introduction %>  </th>
          </tr>
        </tbody>
      </table>
      <div class="userbtn">
        <p><%= link_to "", edit_user_path(@user_id.id),class:"btn btn-outline-secondary btn-block fas fa-user-cog "  %></p>
      </div>

              <h3 class="mt-3">New post</h3>
      <%= form_with model:@post_new, local:true do |f| %>
      <% if @post_new.errors.any? %>
        <div class="alert alert-warning">
          <h2><%= @post_new.errors.count %> errors prohibited this image from being saved:</h2>
            <ul>
              <% @post_new.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
        </div>
            <% end %>

      <i class="fas fa-cat">Image</i>
      <%= f.attachment_field :image %>
      <i class="fas fa-flag">Title</i>
      <%= f.text_field :title, class: "form-control" %>
       <i class= "fas fa-user-edit">Introduction</i>
      <%= f.text_area :content, class: "form-control" %>
      <i class="fas fa-tag">tag</i>
       <%= f.text_field :tag_list, value: @post_new.tag_list.join(','), class: "form-control" %>
      <div class="btn">
        <%= f.submit 'Create Book',class:"btn btn-success" %>
            <% end %>
      </div>
    </div>

      <div class="col-md-8 offset-md-1">
        <div class="card w-75 mx-auto mt-2 shadow-lg">
              <%=attachment_image_tag @post, :image, format: 'jpeg', class:"card-img-top" %>
          <div class="card-body">
            <div class="row">
              <div class="col-2">
              <%= link_to user_path(@user.id) do%> <%= attachment_image_tag @user, :image, format: 'jpeg',  size: "50x50" , class:"mt-3 rounded-circle"; %><% end %><div class="size"><%= link_to users_path(@post.user) do%><% @post.user.name%><% end %></div>
              </div>
              <div class="col-10">
                <div class="card-title">
                  <p><i class="far fa-flag"></i>：<%= @post.title %> </p>
                </div>
                <p  class= "fas fa-user-edit"></p>:<%= @post.content %>
                <div>
                 tag:<% @post.tags.each do |tag|%>
                   <%= link_to "#{tag.name}(#{tag.taggings_count})", posts_path(tag: tag.name), class: "label label-default" %>
                  <%end%>
                 <div id="likes_buttons_<%= @post.id %>">
                   favorites:<%= render "likes/like", post: @post %>
                </div>

              <div>
                <% if @post.user == current_user %>
                <%= link_to "Edit",edit_post_path(@post.id),class:"text-info" %>
                <%= link_to "Destroy", post_path(@post.id), method: :delete, "data-confirm" => "Are you sure?",class:"text-info"%>
                <% end %>
              </div>
            <div>
              <table class="comment_table">
                <tbody id="comments">
                    <%= render partial: "comments", locals: {post: @post, comments: @comments} %>
                </tbody>
              </table>
            </div>

            <div>
                <%= form_with(model: [@post, @comment], method: :post) do |f| %>
                  <%= f.text_area :comment,class:"form-control" %>
                  <%= f.hidden_field :post_id, value: @post.id %>
                  <p class="btn">
                  <%= f.submit 'コメントする',class:"btn btn-primary btn-sm" %>
                  </p>
                <% end %>
          </div>
                </div>
              </div>
            </div>
          </div>
        </div>
       </div>
      <div class="d-flex justify-content-end">
    </div>
  </div>
</div>