config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/about'
  get 'comments/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :users,only:[:index,:show,:edit,:update]
  get 'unsubscribe' => 'users#unsubscribe'
  patch 'withdraw' => 'users#withdraw'
  resources :posts,only:[:index,:show,:new,:edit,:create,:update,:destroy]
  get 'confirm' => 'posts#confirm'
  post 'complete' => 'posts#complete'
  resources :likes,only:[:create,:destroy]
  resources :posts do  #postsコントローラへのルーティング
    resources :comments, only: [:index,:create]  #commentsコントローラへのルーティング
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>matineko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <header>
        <nav class="navbar navbar-expand-lg navbar-light"style="background-color: #008080">
        <div class="container">
           <span class="navbar-bra"> <%= link_to'matineko',homes_about_path,class:"fas fa-cat nav-link text-light" %></span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
       <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to 'Home', user_path(current_user.id),class:"fas fa-home nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to 'User', users_path,class:"fas fa-user nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Post', posts_path,class:"fas fa-paper-plane nav-link text-light" %>
              </li class="nav-item">
                <%= link_to 'Inquiry', inquiry_path,class:"fas fa-clipboard-list nav-link text-light" %>
              <li>

              </li>
              <li class="nav-item">
                <%= link_to "logout", destroy_user_session_path,method: :delete,class:"fas fa-sign-out-alt nav-link text-light"  %>
              </li>
              <li class="search-form">
                <%= search_form_for @search, url: posts_path do |f| %>
                  <div class="input-group">
                    <dt><%= f.text_field :title_cont ,placeholder: 'タイトルを入力...', class: "form-control" %></dt>
                    <dd><%= f.submit ("検索") , class: "btn btn-dark"%></dd>
                  </div>
                <% end %>
              </li>

            </ul>
         </div>
          </div>
         </nav>
        </header>
    <% else %>
     <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
       <li class="nav-item">
        <%= link_to "Home",root_path,class:"fas fa-home nav-link text-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "About",homes_about_path,class:"fas fa-link nav-link text-light"%>
      </li>
      <li class="nav-item">
        <%= link_to "sign up", new_user_registration_path,class:"fas fa-user-plus nav-link text-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "login", new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light" %>
      </li>
    </ul>
    </div>
     </div>
      </nav>
    </header>
    <% end %>
    <main>
      <%= yield %>
    </main>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>